# Generated by Django 5.0.1 on 2026-03-09 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_schedule_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="elective_group",
            field=models.CharField(
                blank=True,
                help_text="Grouping ID for synchronized elective slots",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="is_schedulable",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="ElectiveAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_group", models.CharField(default="A", max_length=50)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.course"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.teacher"
                    ),
                ),
            ],
            options={
                "db_table": "elective_allocations",
                "unique_together": {("course", "teacher", "section_group")},
            },
        ),
        migrations.CreateModel(
            name="ElectiveAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.course"
                    ),
                ),
                (
                    "parent_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expansions",
                        to="core.scheduleentry",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.room"
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elective_assignments",
                        to="core.schedule",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.section"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.teacher"
                    ),
                ),
                (
                    "timeslot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.timeslot"
                    ),
                ),
            ],
            options={
                "db_table": "elective_assignments",
                "unique_together": {("parent_entry", "course", "section")},
            },
        ),
    ]
