# Generated by Django 5.0.1 on 2026-03-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_course_elective_group_course_is_schedulable_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="electiveassignment",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="electiveassignment",
            name="course",
        ),
        migrations.RemoveField(
            model_name="electiveassignment",
            name="parent_entry",
        ),
        migrations.RemoveField(
            model_name="electiveassignment",
            name="room",
        ),
        migrations.RemoveField(
            model_name="electiveassignment",
            name="schedule",
        ),
        migrations.RemoveField(
            model_name="electiveassignment",
            name="section",
        ),
        migrations.RemoveField(
            model_name="electiveassignment",
            name="teacher",
        ),
        migrations.RemoveField(
            model_name="electiveassignment",
            name="timeslot",
        ),
        migrations.AddField(
            model_name="teachercoursemapping",
            name="section_group",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="changerequest",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create New"),
                    ("UPDATE", "Update Existing"),
                    ("DELETE", "Delete"),
                    ("SWAP", "Swap Faculty"),
                ],
                help_text="Type of change requested",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="elective_group",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name="ElectiveAllocation",
        ),
        migrations.DeleteModel(
            name="ElectiveAssignment",
        ),
    ]
