# Generated by Django 5.0.1 on 2026-03-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_electiveassignment_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="scheduleentry",
            unique_together={("schedule", "section", "course", "teacher", "timeslot")},
        ),
    ]
