# Generated by Django 5.0.1 on 2026-03-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_scheduleentry_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_adm",
            field=models.BooleanField(default=False),
        ),
    ]
