# Generated by Django 5.0.1 on 2026-03-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_course_is_adm"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleentry",
            name="session_type",
            field=models.CharField(
                choices=[
                    ("LECTURE", "Core Lecture"),
                    ("TUTORIAL", "Core Tutorial"),
                    ("PRACTICAL", "Practical/Lab"),
                    ("ADM", "Administrative"),
                    ("PE", "Professional Elective"),
                    ("FE", "Free Elective"),
                ],
                default="LECTURE",
                max_length=20,
            ),
        ),
    ]
