# Generated by Django 5.0.1 on 2026-03-11 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_scheduleentry_session_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleentry',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.room'),
        ),
    ]
